name: Godot Push CD

on:
  push:
    paths:
      - '.github/workflows/godot_push.yml'
      - 'export/**'
  pull_request:
    paths:
      - '.github/workflows/godot_push.yml'
      - 'export/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: AWS - Set PEM
      run: |
        echo "${{ secrets.AWS_PEM }}" > temp.pem
        chmod 400 temp.pem
    
    - name: AWS - Exclude last files if exists
      run: |
           ssh -q -o "StrictHostKeyChecking no" -i temp.pem ${{ secrets.AWS_SSH }} \
             rm -r /www/dungeon-dance-dance/*
    
    - name: AWS - Send new files to server
      if: success() || failure()
      run: |
        scp -o "StrictHostKeyChecking no" -i temp.pem  -r \
          export/* ${{ secrets.AWS_SSH }}:/www/dungeon-dance-dance/

    - name: AWS - Clear PEM
      if: always()
      run: rm -f temp.pem
